language: go
go:
  - 1.10.x
branches:
  - master

sudo: required

before_install:
  - chmod +x ./utils.sh

install: ./utils.sh deps

script: ./utils.sh build

before_deploy:
 - git push https://${GitHub_Token}@github.com/Undefined01/fortuna --delete tag staging
 - git tag --delete staging
 - git tag staging

deploy:
  provider: releases
  api_key: ${GitHub_Token}
  file_glob: true
  file: upload/*
  skip_cleanup: true
