language: go
go:
  - 1.10.x
branches:
  - master

sudo: required

before_install:
  - chmod +x ./utils.sh

install: ./utils.sh deps

script: ./utils.sh build

before_deploy:
 - git fetch origin --tag && git tag --list
 - git tag | grep staging | xargs -n1 git push https://${GitHub_Token}@github.com/Undefined01/fortuna --delete tag || echo No Staging tag deleted
 - git tag | grep staging | xargs -n1 git tag --delete || echo No Staging tag deleted
 - git tag staging-$(date "+%m%d-%H%M")

deploy:
  provider: releases
  api_key: ${GitHub_Token}
  file_glob: true
  file: upload/*
  skip_cleanup: true
